Repository m-aaaliii/nuxt3-basic, pull requests merged in 2023-09, with the labels that each got.

#6 header completed
  components/Hamburger.vue
  components/Header.vue
  components/dropdown.vue
Labels: feature

#8 Footer UI completed
  components/Footer.vue
  layouts/default.vue
Labels: feature

#15 7 view all products for category page
  assets/main.scss
  components/Header.vue
  components/cardpage.vue
  components/dropdown.vue
  pages/category.vue
  pages/index.vue
  tailwind.config.js
Labels: feature

#16 9 header image and sub category cards on category page
  assets/main.scss
  components/Footer.vue
  components/Header.vue
  components/SubCatCard.vue
  components/cardpage.vue
  components/dropdown.vue
  components/sliders/RibbonSlider.vue
  layouts/default.vue
  pages/category.vue
  pages/index.vue
  tailwind.config.js
Labels: feature

#17 breadcrumbs completed
  assets/main.scss
  components/BreadCrumbs.vue
  components/card.vue
  components/cardpage.vue
  layouts/default.vue
  pages/category.vue
  pages/index.vue
  tailwind.config.js
Labels: feature

#21 19 sign up page
  pages/signup.vue
Labels: feature

#22 login page created
  pages/login.vue
Labels: feature

#23 Created dynamic links
  components/card.vue
  components/cardpage.vue
  pages/product/[id].vue
Labels: enhancement, feature

#24 header modified
  components/BreadCrumbs.vue
  components/Hamburger.vue
  components/Header.vue
  components/ProductDetail.vue
  components/dropdown.vue
  layouts/default.vue
  pages/category.vue
Labels: enhancement

#25 added order complete page
  pages/orderComplete.vue
Labels: feature

#27 product-detail designing
  pages/product/[id].vue
Labels: feature

#28 11 product details slider and product details on product details page
  components/productSizes.vue
  pages/product/[id].vue
Labels: feature

#29 12 description manufacturer and review tabs on product details page
  components/CommentCard.vue
  components/sliders/HomeSlider.vue
  components/tabs/ProductDescriptionTabs.vue
  pages/product/[id].vue
  public/person1.jpg
  public/person2.jpg
  public/person3.jpg
Labels: feature

#31 icons changed
  components/CommentCard.vue
  components/Footer.vue
  components/Hamburger.vue
  components/Header.vue
  components/ProductDetail.vue
  middleware/auth.ts
  nuxt.config.ts
  pages/[category].vue
  pages/checkout.vue
  pages/orderComplete.vue
  pages/product/[id].vue
  yarn.lock
Labels: feature
